name: rdp
dependencies:
- python=3.10
- pip
- pip:
  - aiohttp==3.8.5
  - aiosignal==1.3.1
  - annotated-types==0.5.0
  - asttokens==2.2.1
  - async-timeout==4.0.2
  - attrs==23.1.0
  - backcall==0.2.0
  - backports.functools-lru-cache==1.6.5
  - bertopic==0.16.4
  - blis==0.7.10
  - branca==0.7.1
  - Brotli==1.0.9
  - catalogue==2.0.9
  - certifi==2024.12.14
  - cffi==1.15.1
  - charset-normalizer==3.2.0
  - click==8.1.6
  - cloudpickle==3.1.0
  - colorama==0.4.6
  - confection==0.1.1
  - contourpy==1.1.0
  - cryptography==41.0.2
  - cycler==0.11.0
  - cymem==2.0.7
  - Cython==3.0.11
  - dataclasses==0.8
  - datasets==2.14.0
  - debugpy==1.6.7
  - decorator==5.1.1
  - dill==0.3.7
  - docopt==0.6.2
  - en-core-web-sm==2.3.1
  - et-xmlfile==1.1.0
  - executing==1.2.0
  - fastjsonschema==2.21.1
  - filelock==3.12.2
  - folium==0.16.0
  - fonttools==4.41.1
  - frozenlist==1.4.0
  - fsspec==2023.6.0
  - greenlet==2.0.2
  - gssapi==1.8.2
  - hdbscan==0.8.39
  - hdfs==2.7.0
  - huggingface-hub==0.26.2
  - idna==3.4
  - importlib-metadata==6.8.0
  - importlib-resources==6.0.0
  - inquirerpy==0.3.4
  - ipykernel==6.15.1
  - ipython==8.14.0
  - jedi==0.18.2
  - Jinja2==3.1.2
  - joblib==1.3.0
  - jsonschema==4.23.0
  - jsonschema-specifications==2024.10.1
  - jupyter_client==8.3.0
  - jupyter_core==5.3.1
  - keybert==0.8.5
  - kiwisolver==1.4.4
  - krb5==0.5.0
  - langcodes==3.3.0
  - llvmlite==0.43.0
  - lxml==4.9.3
  - markdown-it-py==3.0.0
  - MarkupSafe==2.1.3
  - matplotlib==3.7.2
  - matplotlib-inline==0.1.6
  - mdurl==0.1.0
  - multidict==6.0.4
  - multiprocess==0.70.15
  - murmurhash==1.0.9
  - nbformat==5.10.4
  - nest-asyncio==1.5.6
  - numba==0.60.0
  - numpy==1.22.3
  - openpyxl==3.1.2
  - packaging==23.1
  - pandas==1.4.3
  - parso==0.8.3
  - pathy==0.10.2
  - pexpect==4.8.0
  - pfzy==0.3.4
  - pickleshare==0.7.5
  - Pillow==10.0.0
  - pip==23.2.1
  - platformdirs==3.10.0
  - plotly==5.24.1
  - pooch==1.7.0
  - preshed==3.0.8
  - prompt-toolkit==3.0.39
  - psutil==5.9.5
  - ptyprocess==0.7.0
  - pure-eval==0.2.2
  - pyarrow==9.0.0
  - pycparser==2.21
  - pydantic==2.1.1
  - pydantic_core==2.4.0
  - Pygments==2.15.1
  - pynndescent==0.5.13
  - pynvml==11.4.1
  - pyodbc==4.0.34
  - pyparsing==3.0.9
  - PySocks==1.7.1
  - pyspnego==0.9.1
  - python-dateutil==2.8.2
  - python-docx==0.8.11
  - pytz==2023.3
  - PyYAML==6.0
  - pyzmq==25.1.0
  - referencing==0.36.2
  - regex==2023.6.3
  - requests==2.31.0
  - requests-kerberos==0.14.0
  - rich==13.5.1
  - rpds-py==0.22.3
  - sacremoses==0.0.53
  - safetensors==0.4.5
  - scalene==1.5.41
  - scikit-learn==1.3.0
  - scipy==1.11.1
  - seaborn==0.12.2
  - sentence-splitter==1.4
  - sentence-transformers==3.2.1
  - setuptools==68.0.0
  - shellingham==1.5.1
  - six==1.16.0
  - smart-open==5.2.1
  - spacy==3.6.1
  - spacy-legacy==3.0.12
  - spacy-loggers==1.0.4
  - SQLAlchemy==1.4.41
  - srsly==2.4.7
  - stack-data==0.6.2
  - tenacity==9.0.0
  - termcolor==2.3.0
  - thinc==8.1.11
  - threadpoolctl==3.2.0
  - tokenizers==0.20.3
  - torch==1.12.0.post2
  - tornado==6.3.2
  - tqdm==4.65.0
  - traitlets==5.9.0
  - transformers==4.46.2
  - typer==0.9.0
  - typing_extensions==4.7.1
  - umap-learn==0.5.7
  - urllib3==2.0.4
  - wasabi==1.1.2
  - wcwidth==0.2.6
  - wheel==0.41.0
  - XlsxWriter==3.1.2
  - xxhash==0.0.0
  - xyzservices==2024.4.0
  - yarl==1.9.2
  - zipp==3.16.2
